[package]
name = "tinybooter"
version = "1.0.0"
authors = ["Sylvain VISTE <viste.sylvain@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
serde = "1.0.123"
serde_yaml = "0.8.17"
serde_derive = "1.0.123"
glob = "0.3.0"
rocket = "0.4.7"
signal-hook = "0.3.6"
